services:

   pg:
       image: postgres:16-alpine
       environment:
           - POSTGRES_USER=aniclips
           - POSTGRES_PASSWORD=12345678
           - POSTGRES_DB=aniclips
       healthcheck:
           test: ["CMD-SHELL", "pg_isready -U postgres"]
           interval: 30s
           timeout: 30s
           retries: 3
       container_name: postgresql-spring
       restart: on-failure
       ports:
           - "5433:5432"
       volumes:
           - pgdata:/var/lib/postgresql/data

   pgadmin:
       image: dpage/pgadmin4:8.14
       container_name: pgadmin-spring
       restart: always
       ports:
         - "5050:80"
       environment:
         PGADMIN_DEFAULT_EMAIL: admin@admin.com
         PGADMIN_DEFAULT_PASSWORD: 1
       volumes:
         - pgadmin-data:/var/lib/pgadmin

   app:
     build:
       context: .
       dockerfile: Dockerfile
     ports:
       - "8081:8080"
     environment:
       SPRING_DATASOURCE_URL: jdbc:postgresql://pg:5432/aniclips
       SPRING_DATASOURCE_USERNAME: aniclips
       SPRING_DATASOURCE_PASSWORD: 12345678
       SEND_API_KEY: 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

     depends_on:
       - pg
volumes:
  pgdata:
  pgadmin-data:
